# Notebook to join Custom $Values for export suitable for the Ottoneu Value Calculator

In [1]:
League_path = '/Users/cmartin/Fantasy_Baseball/Ottoneu_Baseball_Projects/Imaginary_Hammers/'

In [2]:
Proj_files = {
    'Hitter':'FG_Auction_Jan25_2026/fangraphs-auction-calculator_Hitters.csv',
    'Pitcher':'FG_Auction_Jan25_2026/fangraphs-auction-calculator_Pitchers.csv'
}

In [3]:
Player_ID_Map_Path = '/Users/cmartin/Fantasy_Baseball/Ottoneu_Baseball_Projects/Player_ID_Map/Latest_Player_ID_Map.csv'

In [4]:
import pandas as pd
import numpy as np

In [5]:
Export_Cols = {
    'Ottoneu ID':'otto',
    'Name':'Name',
    'Ottoneu Positions':'Pos',
    'Team':'Team',
    'Dollars':'$'
}

In [6]:
Player_ID_Map_df = pd.read_csv(Player_ID_Map_Path)

In [7]:
Hitter_Proj_df = pd.read_csv(League_path+Proj_files['Hitter'])
Pitcher_Proj_df = pd.read_csv(League_path+Proj_files['Pitcher'])

In [8]:
Hitter_Proj_df.rename(columns={
    'PlayerId':'FG ID'
},inplace=True)
Pitcher_Proj_df.rename(columns={
    'PlayerId':'FG ID'
},inplace=True)

In [9]:
Hitter_Proj_df.head()

,Name,Team,POS,ADP,PA,mR,mHR,mOBP,mSLG,PTS,aPOS,Dollars,NameASCII,FG ID,MLBAMID
0,Aaron Judge,NYY,OF/DH,1.970000,634.656,16.034662,20.114860,25.471800,24.123988,85.745309,19.399045,106.144354,Aaron Judge,15640,592450
1,Shohei Ohtani,LAD,DH,1.110000,658.176,19.858656,20.467864,14.397729,23.820367,78.544617,13.414844,92.959461,Shohei Ohtani,19755,660271
2,Juan Soto,NYM,OF,4.470000,621.171,14.217680,12.187691,23.742689,14.093434,64.241494,19.399045,84.640539,Juan Soto,20123,665742
3,Ronald Acuña Jr.,ATL,OF,7.560000,676.219,16.026135,8.951205,17.472625,10.270725,52.720691,19.399045,73.119736,Ronald Acuna Jr.,18401,660670
4,Yordan Alvarez,HOU,OF/DH,45.860001,550.801,8.138269,8.253472,16.514573,17.192679,50.098993,19.399045,70.498039,Yordan Alvarez,19556,670541

In [10]:
Hitter_Proj_df[Hitter_Proj_df['NameASCII'] == 'Sebastian Walcott'][['FG ID','Dollars','Team']].reset_index(drop=True)

       FG ID    Dollars Team
0  sa3021069 -25.440221  TEX

In [11]:
Hitter_Proj_df[Hitter_Proj_df['NameASCII'] == 'Shohei Ohtani'][['FG ID','Dollars','Team']].reset_index(drop=True)#.iloc[0]

   FG ID    Dollars Team
0  19755  92.959461  LAD

In [12]:
Player_ID_Map_df['FG ID'] = Player_ID_Map_df['FG ID'].astype(str)

In [13]:
Player_ID_Map_df['FG ID'] = Player_ID_Map_df['FG ID'].fillna(Player_ID_Map_df['FG Minor ID'])

In [14]:
Player_ID_Map_df[Player_ID_Map_df['Name'] == 'Sebastian Walcott'].reset_index(drop=True).iloc[0]

Ottoneu ID                       42991
Name                 Sebastian Walcott
FG ID                        sa3021069
FG Minor ID                  sa3021069
MLBAM ID                      806964.0
Birthday                    03/14/2006
Ottoneu Positions                   SS
Name: 0, dtype: object

In [15]:
Player_ID_Map_df[Player_ID_Map_df['Name'] == 'Shohei Ohtani'].reset_index(drop=True).iloc[0]

Ottoneu ID                   33600
Name                 Shohei Ohtani
FG ID                      19755.0
FG Minor ID                    NaN
MLBAM ID                  660271.0
Birthday                07/05/1994
Ottoneu Positions          Util/SP
Name: 0, dtype: object

In [16]:
Player_ID_Map_df['FG ID'] = Player_ID_Map_df['FG ID'].str.replace('.0','')

In [17]:
Hitter_merge = Hitter_Proj_df[['FG ID','Dollars','Team']].merge(Player_ID_Map_df[['FG ID','Ottoneu ID','Ottoneu Positions','Name']],how='inner')

In [18]:
Hitter_merge[Hitter_merge['Name'] == 'Shohei Ohtani']

   FG ID    Dollars Team  Ottoneu ID Ottoneu Positions           Name
1  19755  92.959461  LAD       33600           Util/SP  Shohei Ohtani

In [19]:
Hitter_merge[Hitter_merge['Name'] == 'Sebastian Walcott']

,FG ID,Dollars,Team,Ottoneu ID,Ottoneu Positions,Name
538,sa3021069,-25.440221,TEX,42991,SS,Sebastian Walcott

In [20]:
Pitcher_merge = Pitcher_Proj_df[['FG ID','Dollars','Team']].merge(Player_ID_Map_df[['FG ID','Ottoneu ID','Ottoneu Positions','Name']],how='inner')

In [21]:
Pitcher_merge['Ottoneu Positions'].value_counts()

Ottoneu Positions
RP       312
SP       180
SP/RP     96
Util       1
Name: count, dtype: int64

In [22]:
# Pitcher_merge['POS'] = Pitcher_merge['POS'].map(
#     {
#        "['RP']":"RP",
#        "['SP']":"SP",
#        "['SP', 'RP']":"SP/RP",
#     }
# )

In [23]:
# Hitter_merge['POS'] = Pitcher_merge['POS'].map(
#     {
#        'DH':"Util"
#     }
# )

In [24]:
Pitcher_merge

     FG ID    Dollars Team  Ottoneu ID Ottoneu Positions              Name
0    22267  78.967359  DET       35204                SP      Tarik Skubal
1    33677  65.844947  PIT       43894                SP       Paul Skenes
2    27463  61.984989  BOS       38312                SP   Garrett Crochet
3    10603  47.173739  ATL       14393                SP        Chris Sale
4    10310  37.972307  PHI       15962                SP      Zack Wheeler
..     ...        ...  ...         ...               ...               ...
584  24719 -59.362109  SDP       35440                SP     Randy Vasquez
585  33482 -69.599280  COL       44512                SP   Chase Dollander
586  27669 -69.752356  COL       37200                SP     Tanner Gordon
587  14843 -74.119504  COL       18354                SP  Michael Lorenzen
588  16256 -84.885931  COL       18363                SP     Kyle Freeland

[589 rows x 6 columns]

In [25]:
Hitter_merge[(Hitter_merge['Dollars'] > 0.)]['Dollars'].count()

np.int64(160)

In [26]:
Hitter_merge[(Hitter_merge['Dollars'] >= 0.)]['Dollars'].sum()

np.float64(3184.8412540210757)

In [27]:
Pitcher_merge[(Pitcher_merge['Dollars'] >= 0.)]['Dollars'].sum()

np.float64(1393.0533932039991)

In [28]:
Hitter_Pitcher = pd.concat(
    [
        Hitter_merge,
        Pitcher_merge
    ]
)

In [29]:
Hitter_Pitcher[Hitter_Pitcher['Name'] == 'Sebastian Walcott']

,FG ID,Dollars,Team,Ottoneu ID,Ottoneu Positions,Name
538,sa3021069,-25.440221,TEX,42991,SS,Sebastian Walcott

In [30]:
Hitter_Pitcher[Hitter_Pitcher['FG ID'] == '19755']

   FG ID    Dollars Team  Ottoneu ID Ottoneu Positions           Name
1  19755  92.959461  LAD       33600           Util/SP  Shohei Ohtani

In [31]:
Hitter_Pitcher

     FG ID     Dollars Team  Ottoneu ID Ottoneu Positions              Name
0    15640  106.144354  NYY       18312                OF       Aaron Judge
1    19755   92.959461  LAD       33600           Util/SP     Shohei Ohtani
2    20123   84.640539  NYM       23717                OF         Juan Soto
3    18401   73.119736  ATL       23327                OF  Ronald Acuña Jr.
4    19556   70.498039  HOU       23795                OF    Yordan Alvarez
..     ...         ...  ...         ...               ...               ...
584  24719  -59.362109  SDP       35440                SP     Randy Vasquez
585  33482  -69.599280  COL       44512                SP   Chase Dollander
586  27669  -69.752356  COL       37200                SP     Tanner Gordon
587  14843  -74.119504  COL       18354                SP  Michael Lorenzen
588  16256  -84.885931  COL       18363                SP     Kyle Freeland

[1336 rows x 6 columns]

In [32]:
Hitter_Pitcher[Hitter_Pitcher['FG ID'] == '3137']

    FG ID    Dollars Team  Ottoneu ID Ottoneu Positions          Name
466  3137 -16.586005  NaN        4514                SP  Max Scherzer

In [33]:
Hitter_Pitcher['FG ID'].value_counts().reset_index()

      FG ID  count
0     15640      1
1     19755      1
2     20123      1
3     18401      1
4     19556      1
...     ...    ...
1331  24719      1
1332  33482      1
1333  27669      1
1334  14843      1
1335  16256      1

[1336 rows x 2 columns]

In [34]:
Final_df = Hitter_Pitcher.rename(columns=Export_Cols)[[val for key,val in Export_Cols.items()]]

In [35]:
Final_df.sort_values('$',ascending=False).reset_index(drop=True)

       otto              Name      Pos Team           $
0     18312       Aaron Judge       OF  NYY  106.144354
1     33600     Shohei Ohtani  Util/SP  LAD   92.959461
2     23717         Juan Soto       OF  NYM   84.640539
3     35204      Tarik Skubal       SP  DET   78.967359
4     23327  Ronald Acuña Jr.       OF  ATL   73.119736
...     ...               ...      ...  ...         ...
1331  35440     Randy Vasquez       SP  SDP  -59.362109
1332  44512   Chase Dollander       SP  COL  -69.599280
1333  37200     Tanner Gordon       SP  COL  -69.752356
1334  18354  Michael Lorenzen       SP  COL  -74.119504
1335  18363     Kyle Freeland       SP  COL  -84.885931

[1336 rows x 5 columns]

In [36]:
Final_df.sort_values('$',ascending=False).reset_index(drop=True).to_csv(League_path+'Ottoneu_Value_Calc_FG_Auction_Values.csv',index=False)