# Notebook to join Custom $Values for export suitable for the Ottoneu Value Calculator

In [1]:
League_path = '/Users/cmartin/Fantasy_Baseball/Ottoneu_Baseball_Projects/Imaginary_Hammers/'

In [2]:
Proj_files = {
    'Hitter':'FG_Auction_Mar21_2026/fangraphs-auction-calculator_Hitters.csv',
    'Pitcher':'FG_Auction_Mar21_2026/fangraphs-auction-calculator_Pitchers.csv'
}

In [3]:
Player_ID_Map_Path = '/Users/cmartin/Fantasy_Baseball/Ottoneu_Baseball_Projects/Player_ID_Map/Latest_Player_ID_Map.csv'

In [4]:
import pandas as pd
import numpy as np

In [5]:
Export_Cols = {
    'Ottoneu ID':'otto',
    'Name':'Name',
    'Ottoneu Positions':'Pos',
    'Team':'Team',
    'Dollars':'$'
}

In [6]:
Player_ID_Map_df = pd.read_csv(Player_ID_Map_Path)

In [7]:
Hitter_Proj_df = pd.read_csv(League_path+Proj_files['Hitter'])
Pitcher_Proj_df = pd.read_csv(League_path+Proj_files['Pitcher'])

In [8]:
Hitter_Proj_df.rename(columns={
    'PlayerId':'FG ID'
},inplace=True)
Pitcher_Proj_df.rename(columns={
    'PlayerId':'FG ID'
},inplace=True)

In [9]:
Hitter_Proj_df.head()

,Name,Team,POS,ADP,PA,mR,mHR,mOBP,mSLG,PTS,aPOS,Dollars,NameASCII,FG ID,MLBAMID
0,Aaron Judge,NYY,OF/DH,1.850000,644,7.659727,9.406973,14.084419,12.220187,43.371306,11.814599,56.185905,Aaron Judge,15640,592450
1,Shohei Ohtani,LAD,DH,1.250000,679,11.220638,11.538463,9.356424,14.706769,46.822294,8.135422,55.957716,Shohei Ohtani,19755,660271
2,Juan Soto,NYM,OF,4.600000,686,8.253212,7.275484,13.941831,7.831643,37.302171,11.814599,50.116769,Juan Soto,20123,665742
3,Ronald Acuña Jr.,ATL,OF,5.430000,651,8.451041,4.291399,10.440860,6.239615,29.422914,11.814599,42.237513,Ronald Acuna Jr.,18401,660670
4,Kyle Schwarber,PHI,OF/DH,24.110001,686,6.077100,9.833271,2.913095,5.293933,24.117399,11.814599,36.931998,Kyle Schwarber,16478,656941

In [10]:
Hitter_Proj_df[Hitter_Proj_df['NameASCII'] == 'Sebastian Walcott'][['FG ID','Dollars','Team']].reset_index(drop=True)

Empty DataFrame
Columns: [FG ID, Dollars, Team]
Index: []

In [11]:
Hitter_Proj_df[Hitter_Proj_df['NameASCII'] == 'Shohei Ohtani'][['FG ID','Dollars','Team']].reset_index(drop=True)#.iloc[0]

   FG ID    Dollars Team
0  19755  55.957716  LAD

In [12]:
Player_ID_Map_df['FG ID'] = Player_ID_Map_df['FG ID'].astype(str)

In [13]:
Player_ID_Map_df['FG ID'] = Player_ID_Map_df['FG ID'].fillna(Player_ID_Map_df['FG Minor ID'])

In [14]:
Player_ID_Map_df[Player_ID_Map_df['Name'] == 'Sebastian Walcott'].reset_index(drop=True).iloc[0]

Ottoneu ID                       42991
Name                 Sebastian Walcott
FG ID                        sa3021069
FG Minor ID                  sa3021069
MLBAM ID                      806964.0
Birthday                    03/14/2006
Ottoneu Positions                   SS
Name: 0, dtype: object

In [15]:
Player_ID_Map_df[Player_ID_Map_df['Name'] == 'Shohei Ohtani'].reset_index(drop=True).iloc[0]

Ottoneu ID                   33600
Name                 Shohei Ohtani
FG ID                      19755.0
FG Minor ID                    NaN
MLBAM ID                  660271.0
Birthday                07/05/1994
Ottoneu Positions          Util/SP
Name: 0, dtype: object

In [16]:
Player_ID_Map_df['FG ID'] = Player_ID_Map_df['FG ID'].str.replace('.0','')

In [17]:
Hitter_merge = Hitter_Proj_df[['FG ID','Dollars','Team']].merge(Player_ID_Map_df[['FG ID','Ottoneu ID','Ottoneu Positions','Name']],how='inner')

In [18]:
Hitter_merge[Hitter_merge['Name'] == 'Shohei Ohtani']

   FG ID    Dollars Team  Ottoneu ID Ottoneu Positions           Name
1  19755  55.957716  LAD       33600           Util/SP  Shohei Ohtani

In [19]:
Hitter_merge[Hitter_merge['Name'] == 'Sebastian Walcott']

Empty DataFrame
Columns: [FG ID, Dollars, Team, Ottoneu ID, Ottoneu Positions, Name]
Index: []

In [20]:
Pitcher_merge = Pitcher_Proj_df[['FG ID','Dollars','Team']].merge(Player_ID_Map_df[['FG ID','Ottoneu ID','Ottoneu Positions','Name']],how='inner')

In [21]:
Pitcher_merge['Ottoneu Positions'].value_counts()

Ottoneu Positions
RP         282
SP         164
SP/RP       83
Util/SP      1
Util         1
Name: count, dtype: int64

In [22]:
# Pitcher_merge['POS'] = Pitcher_merge['POS'].map(
#     {
#        "['RP']":"RP",
#        "['SP']":"SP",
#        "['SP', 'RP']":"SP/RP",
#     }
# )

In [23]:
# Hitter_merge['POS'] = Pitcher_merge['POS'].map(
#     {
#        'DH':"Util"
#     }
# )

In [24]:
Pitcher_merge

     FG ID    Dollars Team  Ottoneu ID Ottoneu Positions                Name
0    22267  89.574658  DET       35204                SP        Tarik Skubal
1    33677  71.558654  PIT       43894                SP         Paul Skenes
2    27463  68.899664  BOS       38312                SP     Garrett Crochet
3    17995  50.081321  SFG       21015                SP          Logan Webb
4    20778  49.712471  PHI       20975                SP  Cristopher Sanchez
..     ...        ...  ...         ...               ...                 ...
526  33482 -33.413412  COL       44512                SP     Chase Dollander
527  16256 -33.845651  COL       18363                SP       Kyle Freeland
528  35321 -34.020113  COL       46090                SP     Tomoyuki Sugano
529  14843 -35.790229  COL       18354                SP    Michael Lorenzen
530  15488 -36.699212  COL       23757             SP/RP   Antonio Senzatela

[531 rows x 6 columns]

In [25]:
Hitter_merge[(Hitter_merge['Dollars'] > 0.)]['Dollars'].count()

np.int64(216)

In [26]:
Hitter_merge[(Hitter_merge['Dollars'] >= 0.)]['Dollars'].sum()

np.float64(2439.3455236011973)

In [27]:
Pitcher_merge[(Pitcher_merge['Dollars'] >= 0.)]['Dollars'].sum()

np.float64(2151.262538824346)

In [28]:
Hitter_Pitcher = pd.concat(
    [
        Hitter_merge,
        Pitcher_merge
    ]
)

In [29]:
Hitter_Pitcher[Hitter_Pitcher['Name'] == 'Sebastian Walcott']

Empty DataFrame
Columns: [FG ID, Dollars, Team, Ottoneu ID, Ottoneu Positions, Name]
Index: []

In [30]:
Hitter_Pitcher[Hitter_Pitcher['FG ID'] == '19755']

    FG ID    Dollars Team  Ottoneu ID Ottoneu Positions           Name
1   19755  55.957716  LAD       33600           Util/SP  Shohei Ohtani
23  19755  23.448734  LAD       33600           Util/SP  Shohei Ohtani

In [31]:
Hitter_Pitcher

     FG ID    Dollars Team  Ottoneu ID Ottoneu Positions               Name
0    15640  56.185905  NYY       18312                OF        Aaron Judge
1    19755  55.957716  LAD       33600           Util/SP      Shohei Ohtani
2    20123  50.116769  NYM       23717                OF          Juan Soto
3    18401  42.237513  ATL       23327                OF   Ronald Acuña Jr.
4    16478  36.931998  PHI       18347                OF     Kyle Schwarber
..     ...        ...  ...         ...               ...                ...
526  33482 -33.413412  COL       44512                SP    Chase Dollander
527  16256 -33.845651  COL       18363                SP      Kyle Freeland
528  35321 -34.020113  COL       46090                SP    Tomoyuki Sugano
529  14843 -35.790229  COL       18354                SP   Michael Lorenzen
530  15488 -36.699212  COL       23757             SP/RP  Antonio Senzatela

[1166 rows x 6 columns]

In [32]:
Hitter_Pitcher[Hitter_Pitcher['FG ID'] == '3137']

    FG ID   Dollars Team  Ottoneu ID Ottoneu Positions          Name
150  3137  2.102857  TOR        4514                SP  Max Scherzer

In [33]:
Hitter_Pitcher['FG ID'].value_counts().reset_index()

      FG ID  count
0     19755      2
1     13757      2
2     15640      1
3     20123      1
4     18401      1
...     ...    ...
1159  33482      1
1160  16256      1
1161  35321      1
1162  14843      1
1163  15488      1

[1164 rows x 2 columns]

In [34]:
Final_df = Hitter_Pitcher.rename(columns=Export_Cols)[[val for key,val in Export_Cols.items()]]

In [35]:
Final_df.sort_values('$',ascending=False).reset_index(drop=True)

       otto               Name      Pos Team          $
0     35204       Tarik Skubal       SP  DET  89.574658
1     43894        Paul Skenes       SP  PIT  71.558654
2     38312    Garrett Crochet       SP  BOS  68.899664
3     18312        Aaron Judge       OF  NYY  56.185905
4     33600      Shohei Ohtani  Util/SP  LAD  55.957716
...     ...                ...      ...  ...        ...
1161  44512    Chase Dollander       SP  COL -33.413412
1162  18363      Kyle Freeland       SP  COL -33.845651
1163  46090    Tomoyuki Sugano       SP  COL -34.020113
1164  18354   Michael Lorenzen       SP  COL -35.790229
1165  23757  Antonio Senzatela    SP/RP  COL -36.699212

[1166 rows x 5 columns]

In [36]:
Final_df.sort_values('$',ascending=False).reset_index(drop=True).to_csv(League_path+'Ottoneu_Value_Calc_FG_Auction_Values.csv',index=False)