# Notebook to join Custom $Values for export suitable for the Ottoneu Value Calculator

In [1]:
League_path = '/Users/cmartin/Fantasy_Baseball/Ottoneu_Baseball_Projects/Imaginary_Hammers/'

In [2]:
Proj_files = {
    'Hitter':'Latest_Hitter_Proj.csv',
    'Pitcher':'Latest_Pitcher_Proj.csv'
}

In [3]:
Player_ID_Map_Path = '/Users/cmartin/Fantasy_Baseball/Ottoneu_Baseball_Projects/Player_ID_Map/Latest_Player_ID_Map.csv'

In [4]:
import pandas as pd
import numpy as np

In [5]:
Export_Cols = {
    'Ottoneu ID':'otto',
    'Name':'Name',
    'Ottoneu Positions':'Pos',
    'Team':'Team',
    'TOTAL_SGP_Val':'$'
}

In [6]:
Player_ID_Map_df = pd.read_csv(Player_ID_Map_Path)

In [7]:
Hitter_Proj_df = pd.read_csv(League_path+Proj_files['Hitter'])
Pitcher_Proj_df = pd.read_csv(League_path+Proj_files['Pitcher'])

In [8]:
Hitter_Proj_df.rename(columns={
    'PlayerId':'FG ID'
},inplace=True)
Pitcher_Proj_df.rename(columns={
    'PlayerId':'FG ID'
},inplace=True)

In [9]:
Hitter_Proj_df[Hitter_Proj_df['Name'] == 'Sebastian Walcott'][['FG ID','TOTAL_SGP_Val','Team']].reset_index(drop=True).iloc[0]

FG ID            sa3021069
TOTAL_SGP_Val    -3.045438
Team                   TEX
Name: 0, dtype: object

In [10]:
Hitter_Proj_df[Hitter_Proj_df['Name'] == 'Shohei Ohtani'][['FG ID','TOTAL_SGP_Val','Team']].reset_index(drop=True).iloc[0]

FG ID                19755
TOTAL_SGP_Val    48.426564
Team                   LAD
Name: 0, dtype: object

In [11]:
Player_ID_Map_df['FG ID'] = Player_ID_Map_df['FG ID'].astype(str)

In [12]:
Player_ID_Map_df['FG ID'] = Player_ID_Map_df['FG ID'].fillna(Player_ID_Map_df['FG Minor ID'])

In [13]:
Player_ID_Map_df[Player_ID_Map_df['Name'] == 'Sebastian Walcott'].reset_index(drop=True).iloc[0]

Ottoneu ID                       42991
Name                 Sebastian Walcott
FG ID                        sa3021069
FG Minor ID                  sa3021069
MLBAM ID                        806964
Birthday                    03/14/2006
Ottoneu Positions                   SS
Name: 0, dtype: object

In [14]:
Player_ID_Map_df[Player_ID_Map_df['Name'] == 'Shohei Ohtani'].reset_index(drop=True).iloc[0]

Ottoneu ID                   33600
Name                 Shohei Ohtani
FG ID                      19755.0
FG Minor ID                    NaN
MLBAM ID                    660271
Birthday                07/05/1994
Ottoneu Positions          Util/SP
Name: 0, dtype: object

In [15]:
Player_ID_Map_df['FG ID'] = Player_ID_Map_df['FG ID'].str.replace('.0','')

In [16]:
Hitter_merge = Hitter_Proj_df[['FG ID','TOTAL_SGP_Val','Team','POS']].merge(Player_ID_Map_df[['FG ID','Ottoneu ID','Ottoneu Positions','Name']],how='inner')

In [17]:
Hitter_merge[Hitter_merge['Name'] == 'Shohei Ohtani']

,FG ID,TOTAL_SGP_Val,Team,POS,Ottoneu ID,Ottoneu Positions,Name
168,19755,48.426564,LAD,['DH'],33600,Util/SP,Shohei Ohtani

In [18]:
Hitter_merge[Hitter_merge['Name'] == 'Sebastian Walcott']

,FG ID,TOTAL_SGP_Val,Team,POS,Ottoneu ID,Ottoneu Positions,Name
1179,sa3021069,-3.045438,TEX,['SS'],42991,SS,Sebastian Walcott

In [19]:
Pitcher_merge = Pitcher_Proj_df[['FG ID','TOTAL_SGP_Val','Team','POS']].merge(Player_ID_Map_df[['FG ID','Ottoneu ID','Ottoneu Positions','Name']],how='inner')

In [20]:
Pitcher_merge['Ottoneu Positions'].value_counts()

Ottoneu Positions
RP         413
SP         236
SP/RP      149
Util        10
Util/SP      1
Name: count, dtype: int64

In [21]:
# Pitcher_merge['POS'] = Pitcher_merge['POS'].map(
#     {
#        "['RP']":"RP",
#        "['SP']":"SP",
#        "['SP', 'RP']":"SP/RP",
#     }
# )

In [22]:
# Hitter_merge['POS'] = Pitcher_merge['POS'].map(
#     {
#        'DH':"Util"
#     }
# )

In [23]:
Pitcher_merge

,FG ID,TOTAL_SGP_Val,Team,POS,Ottoneu ID,Ottoneu Positions,Name
0,10061,-1.204217,NYM,['RP'],4970,RP,Brooks Raley
1,10078,0.417795,CHC,['RP'],6225,RP,Caleb Thielbar
2,10233,19.685908,BOS,['RP'],5644,RP,Aroldis Chapman
3,10310,17.447224,PHI,['SP'],15962,SP,Zack Wheeler
4,10315,-11.542711,MIN,['RP'],12068,RP,Michael Tonkin
...,...,...,...,...,...,...,...
804,sa3034016,-5.624415,BOS,['SP'],46203,SP/RP,John Holobetz
805,sa3034986,-4.424573,ATH,['SP'],46221,SP,Gage Jump
806,sa3035282,-5.752815,WSN,['SP'],46223,SP,Jackson Kent
807,sa918182,-5.278150,CIN,['SP'],32716,Util,Julian Garcia
808,sa944989,-2.642284,SDP,['RP'],33510,RP,Daison Acosta

In [24]:
Hitter_merge[(Hitter_merge['TOTAL_SGP_Val'] > -1.)]['TOTAL_SGP_Val'].count()

np.int64(236)

In [25]:
Hitter_merge[(Hitter_merge['TOTAL_SGP_Val'] >= 1.)]['TOTAL_SGP_Val'].sum()

np.float64(2523.08762256219)

In [26]:
Pitcher_merge[(Pitcher_merge['TOTAL_SGP_Val'] >= 1.)]['TOTAL_SGP_Val'].sum()

np.float64(2217.492887760089)

In [27]:
Hitter_Pitcher = pd.concat(
    [
        Hitter_merge,
        Pitcher_merge
    ]
)

In [28]:
Hitter_Pitcher[Hitter_Pitcher['Name'] == 'Sebastian Walcott']

,FG ID,TOTAL_SGP_Val,Team,POS,Ottoneu ID,Ottoneu Positions,Name
1179,sa3021069,-3.045438,TEX,['SS'],42991,SS,Sebastian Walcott

In [29]:
Hitter_Pitcher[Hitter_Pitcher['Name'] == 'Shohei Ohtani']

,FG ID,TOTAL_SGP_Val,Team,POS,Ottoneu ID,Ottoneu Positions,Name
168,19755,48.426564,LAD,['DH'],33600,Util/SP,Shohei Ohtani
187,19755,15.575248,LAD,['SP'],33600,Util/SP,Shohei Ohtani

In [30]:
Hitter_Pitcher[Hitter_Pitcher['FG ID'].isin([key for key, val in Hitter_Pitcher['FG ID'].value_counts().to_dict().items() if val > 1])].sort_values('Name')

,FG ID,TOTAL_SGP_Val,Team,POS,Ottoneu ID,Ottoneu Positions,Name
168,19755,48.426564,LAD,['DH'],33600,Util/SP,Shohei Ohtani
187,19755,15.575248,LAD,['SP'],33600,Util/SP,Shohei Ohtani

In [31]:
#Handle Othtani...
Ohtani_Value = Hitter_Pitcher[Hitter_Pitcher['FG ID'] == '19755']['TOTAL_SGP_Val'].sum()
Ohtani_df = pd.DataFrame([
    {
        'FG ID':'19755',
        'TOTAL_SGP_Val':Ohtani_Value,
        'Team':'LAD',
        'POS':"['DH','SP']",
        'Ottoneu ID':33600,
        'Ottoneu Positions':'Util/SP',
        'Name':'Shohei Ohtani'
    }
])

In [32]:
Hitter_Pitcher.drop_duplicates(['FG ID'],keep=False,inplace=True)

In [33]:
Hitter_Pitcher = pd.concat([
    Hitter_Pitcher,
    Ohtani_df
])

In [34]:
Hitter_Pitcher[Hitter_Pitcher['FG ID'].isin([key for key, val in Hitter_Pitcher['FG ID'].value_counts().to_dict().items() if val > 1])].sort_values('Name')

Empty DataFrame
Columns: [FG ID, TOTAL_SGP_Val, Team, POS, Ottoneu ID, Ottoneu Positions, Name]
Index: []

In [35]:
Final_df = Hitter_Pitcher.rename(columns=Export_Cols)[[val for key,val in Export_Cols.items()]]

In [36]:
Final_df = Final_df.sort_values('$',ascending=False).reset_index(drop=True)

In [37]:
Final_df.to_csv(League_path+'Ottoneu_Value_Calc_Custom$Values.csv',index=False)